NGL: GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false > Class Template Reference
GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false > Class Template Reference
Public Member Functions
NumberStream (GenericReader &reader, InputStream &s)
~NumberStream ()
RAPIDJSON_FORCEINLINE Ch Peek () const
RAPIDJSON_FORCEINLINE Ch TakePush ()
RAPIDJSON_FORCEINLINE Ch Take ()
size_t Tell ()
size_t Length ()
const char * Pop ()
Protected Member Functions
NumberStream & operator= (const NumberStream &)
Protected Attributes
InputStream & is
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator>
template<typename InputStream>
class GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >
Definition at line 730 of file reader.h.
Constructor & Destructor Documentation
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::NumberStream (GenericReader & reader, InputStream & s) inline
Definition at line 732 of file reader.h.
References void().
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::~NumberStream () inline
Definition at line 733 of file reader.h.
Member Function Documentation
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::Length () inline
Definition at line 739 of file reader.h.
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > NumberStream& GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::operator= (const NumberStream< InputStream, false > &) protected
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::Peek () const inline
Definition at line 735 of file reader.h.
References GenericStringStream< Encoding >::Peek().
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > const char* GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::Pop () inline
Definition at line 740 of file reader.h.
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::Take () inline
Definition at line 737 of file reader.h.
References GenericStringStream< Encoding >::Take().
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > RAPIDJSON_FORCEINLINE Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::TakePush () inline
Definition at line 736 of file reader.h.
References GenericStringStream< Encoding >::Take().
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::Tell () inline
Definition at line 738 of file reader.h.
References GenericStringStream< Encoding >::Tell().
Member Data Documentation
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream > InputStream& GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::NumberStream< InputStream, false >::is protected
Definition at line 745 of file reader.h.
The documentation for this class was generated from the following file:
reader.h