NGL: fmt::PrintfFormatter< Char, ArgFormatter > Class Template Reference
fmt::PrintfFormatter< Char, ArgFormatter > Class Template Reference
#include <printf.h>
Public Member Functions
PrintfFormatter (const ArgList &args, BasicWriter< Char > &w)
FMT_API void format (BasicCStringRef< Char > format_str)
Private Member Functions
void parse_flags (FormatSpec &spec, const Char *&s)
internal::Arg get_arg (const Char *s, unsigned arg_index=(std::numeric_limits< unsigned >::max)())
unsigned parse_header (const Char *&s, FormatSpec &spec)
Private Member Functions inherited from fmt::internal::FormatterBase
const ArgList & args () const
FormatterBase (const ArgList &args)
Arg next_arg (const char *&error)
Arg get_arg (unsigned arg_index, const char *&error)
bool check_no_auto_index (const char *&error)
template<typename Char >
void write (BasicWriter< Char > &w, const Char *start, const Char *end)
Private Attributes
BasicWriter< Char > & writer_
Detailed Description
template<typename Char, typename ArgFormatter = PrintfArgFormatter<Char>>
class fmt::PrintfFormatter< Char, ArgFormatter >
This template formats data and writes the output to a writer.
Definition at line 284 of file printf.h.
Constructor & Destructor Documentation
template<typename Char, typename ArgFormatter = PrintfArgFormatter<Char>> fmt::PrintfFormatter< Char, ArgFormatter >::PrintfFormatter (const ArgList & args, BasicWriter< Char > & w) inline explicit
Constructs a PrintfFormatter object. References to the arguments and the writer are stored in the formatter object so make sure they have appropriate lifetimes.
Definition at line 307 of file printf.h.
References FMT_API, and fmt::format().
Member Function Documentation
template<typename Char , typename AF > void fmt::PrintfFormatter< Char, AF >::format (BasicCStringRef< Char > format_str)
Formats stored arguments and writes the output to the writer.
Definition at line 387 of file printf.h.
References fmt::AlignSpec::align_, fmt::ALIGN_NUMERIC, fmt::ALIGN_RIGHT, fmt::arg(), fmt::BasicCStringRef< Char >::c_str(), fmt::WidthSpec::fill_, fmt::FormatSpec::flag(), fmt::FormatSpec::flags_, FMT_THROW, fmt::HASH_FLAG, fmt::internal::Value::LAST_INTEGER_TYPE, fmt::internal::Value::LAST_NUMERIC_TYPE, fmt::internal::parse_nonnegative_int(), fmt::FormatSpec::precision_, fmt::FormatSpec::type_, fmt::ArgVisitor< Impl, Result >::visit(), and fmt::internal::write().
template<typename Char , typename AF > internal::Arg fmt::PrintfFormatter< Char, AF >::get_arg (const Char * s, unsigned arg_index = (std::numeric_limits<unsigned>::max)()) private
Definition at line 341 of file printf.h.
References fmt::arg(), FMT_THROW, fmt::internal::FormatterBase::get_arg(), and void().
template<typename Char , typename AF > void fmt::PrintfFormatter< Char, AF >::parse_flags (FormatSpec & spec, const Char *& s) private
Definition at line 315 of file printf.h.
References fmt::AlignSpec::align_, fmt::ALIGN_LEFT, fmt::WidthSpec::fill_, fmt::FormatSpec::flags_, fmt::HASH_FLAG, fmt::PLUS_FLAG, and fmt::SIGN_FLAG.
template<typename Char , typename AF > unsigned fmt::PrintfFormatter< Char, AF >::parse_header (const Char *& s, FormatSpec & spec) private
Definition at line 353 of file printf.h.
References fmt::WidthSpec::fill_, fmt::internal::parse_nonnegative_int(), fmt::ArgVisitor< Impl, Result >::visit(), and fmt::WidthSpec::width_.
Member Data Documentation
template<typename Char, typename ArgFormatter = PrintfArgFormatter<Char>> BasicWriter<Char>& fmt::PrintfFormatter< Char, ArgFormatter >::writer_ private
Definition at line 286 of file printf.h.
The documentation for this class was generated from the following files:
printf.h
format.cc