NGL: fmt::internal::FormatBuf< Char > Class Template Reference
fmt::internal::FormatBuf< Char > Class Template Reference
#include <ostream.h>
Public Member Functions
FormatBuf (Buffer< Char > &buffer)
int_type overflow (int_type ch=traits_type::eof())
size_t size () const
Private Types
typedef std::basic_streambuf< Char >::int_type int_type
typedef std::basic_streambuf< Char >::traits_type traits_type
Private Attributes
Buffer< Char > & buffer_
Char * start_
Detailed Description
template<class Char>
class fmt::internal::FormatBuf< Char >
Definition at line 21 of file ostream.h.
Member Typedef Documentation
template<class Char> typedef std::basic_streambuf<Char>::int_type fmt::internal::FormatBuf< Char >::int_type private
Definition at line 23 of file ostream.h.
template<class Char> typedef std::basic_streambuf<Char>::traits_type fmt::internal::FormatBuf< Char >::traits_type private
Definition at line 24 of file ostream.h.
Constructor & Destructor Documentation
template<class Char> fmt::internal::FormatBuf< Char >::FormatBuf (Buffer< Char > & buffer) inline
Definition at line 30 of file ostream.h.
References fmt::Buffer< T >::capacity().
Member Function Documentation
template<class Char> int_type fmt::internal::FormatBuf< Char >::overflow (int_type ch = traits_type::eof()) inline
Definition at line 34 of file ostream.h.
References fmt::Buffer< T >::reserve(), fmt::Buffer< T >::resize(), and fmt::internal::FormatBuf< Char >::size().
template<class Char> size_t fmt::internal::FormatBuf< Char >::size () const inline
Definition at line 47 of file ostream.h.
References fmt::internal::convert(), and fmt::internal::to_unsigned().
Member Data Documentation
template<class Char> Buffer<Char>& fmt::internal::FormatBuf< Char >::buffer_ private
Definition at line 26 of file ostream.h.
template<class Char> Char* fmt::internal::FormatBuf< Char >::start_ private
Definition at line 27 of file ostream.h.
The documentation for this class was generated from the following file:
ostream.h