NGL: fmt::internal::ThousandsSep Class Reference
fmt::internal::ThousandsSep Class Reference
#include <format.h>
Public Member Functions
ThousandsSep (fmt::StringRef sep)
template<typename Char >
void operator() (Char *&buffer)
Private Attributes
fmt::StringRef sep_
unsigned digit_index_
Detailed Description
Definition at line 895 of file format.h.
Constructor & Destructor Documentation
fmt::internal::ThousandsSep::ThousandsSep (fmt::StringRef sep) inline explicit
Definition at line 903 of file format.h.
Member Function Documentation
template<typename Char > void fmt::internal::ThousandsSep::operator() (Char *& buffer) inline
Definition at line 906 of file format.h.
References fmt::BasicStringRef< Char >::data(), fmt::internal::make_ptr(), and fmt::BasicStringRef< Char >::size().
Member Data Documentation
unsigned fmt::internal::ThousandsSep::digit_index_ private
Definition at line 900 of file format.h.
fmt::StringRef fmt::internal::ThousandsSep::sep_ private
Definition at line 897 of file format.h.
The documentation for this class was generated from the following file:
format.h