NGL: fmt::BasicFormatter< CharType, ArgFormatter > Class Template Reference
fmt::BasicFormatter< CharType, ArgFormatter > Class Template Reference
#include <format.h>
Public Types
typedef CharType Char
Public Member Functions
BasicFormatter (const ArgList &args, BasicWriter< Char > &w)
BasicWriter< Char > & writer ()
void format (BasicCStringRef< Char > format_str)
const Char * format (const Char *&format_str, const internal::Arg &arg)
Private Member Functions
FMT_DISALLOW_COPY_AND_ASSIGN (BasicFormatter)
internal::Arg get_arg (BasicStringRef< Char > arg_name, const char *&error)
internal::Arg parse_arg_index (const Char *&s)
internal::Arg parse_arg_name (const Char *&s)
Private Member Functions inherited from fmt::internal::FormatterBase
const ArgList & args () const
FormatterBase (const ArgList &args)
Arg next_arg (const char *&error)
Arg get_arg (unsigned arg_index, const char *&error)
bool check_no_auto_index (const char *&error)
template<typename Char >
void write (BasicWriter< Char > &w, const Char *start, const Char *end)
Private Attributes
BasicWriter< Char > & writer_
internal::ArgMap< Char > map_
Detailed Description
template<typename CharType, typename ArgFormatter>
class fmt::BasicFormatter< CharType, ArgFormatter >
This template formats data and writes the output to a writer.
Definition at line 389 of file format.h.
Member Typedef Documentation
template<typename CharType, typename ArgFormatter> typedef CharType fmt::BasicFormatter< CharType, ArgFormatter >::Char
The character type for the output.
Definition at line 2037 of file format.h.
Constructor & Destructor Documentation
template<typename CharType, typename ArgFormatter> fmt::BasicFormatter< CharType, ArgFormatter >::BasicFormatter (const ArgList & args, BasicWriter< Char > & w) inline
Constructs a BasicFormatter object. References to the arguments and the writer are stored in the formatter object so make sure they have appropriate lifetimes.
Definition at line 2065 of file format.h.
Member Function Documentation
template<typename CharType, typename ArgFormatter> fmt::BasicFormatter< CharType, ArgFormatter >::FMT_DISALLOW_COPY_AND_ASSIGN (BasicFormatter< CharType, ArgFormatter >) private
template<typename Char , typename AF > void fmt::BasicFormatter< Char, AF >::format (BasicCStringRef< Char > format_str)
Formats stored arguments and writes the output to the writer.
Definition at line 3734 of file format.h.
References fmt::arg(), fmt::BasicCStringRef< Char >::c_str(), FMT_THROW, fmt::format(), fmt::internal::is_name_start(), and fmt::internal::write().
template<typename Char , typename ArgFormatter > const Char * fmt::BasicFormatter< Char, ArgFormatter >::format (const Char *& format_str, const internal::Arg & arg)
Definition at line 3564 of file format.h.
References fmt::AlignSpec::align_, fmt::ALIGN_CENTER, fmt::ALIGN_DEFAULT, fmt::ALIGN_LEFT, fmt::ALIGN_NUMERIC, fmt::ALIGN_RIGHT, fmt::internal::check_sign(), fmt::internal::Value::custom, fmt::internal::Value::CUSTOM, fmt::WidthSpec::fill_, fmt::FormatSpec::flags_, FMT_THROW, fmt::internal::Value::CustomValue::format, fmt::format(), fmt::HASH_FLAG, fmt::internal::Value::INT, fmt::internal::Value::int_value, fmt::internal::is_name_start(), fmt::internal::Value::LAST_INTEGER_TYPE, fmt::internal::Value::LONG_LONG, fmt::internal::Value::long_long_value, fmt::MINUS_FLAG, fmt::internal::parse_nonnegative_int(), fmt::PLUS_FLAG, fmt::internal::Value::POINTER, fmt::FormatSpec::precision_, fmt::internal::require_numeric_argument(), fmt::SIGN_FLAG, fmt::internal::Arg::type, fmt::FormatSpec::type_, fmt::internal::Value::UINT, fmt::internal::Value::uint_value, fmt::internal::Value::ULONG_LONG, fmt::internal::Value::ulong_long_value, fmt::internal::Value::CustomValue::value, and fmt::WidthSpec::width_.
template<typename Char , typename AF > internal::Arg fmt::BasicFormatter< Char, AF >::get_arg (BasicStringRef< Char > arg_name, const char *& error) inline private
Definition at line 3524 of file format.h.
References fmt::arg().
template<typename Char , typename AF > internal::Arg fmt::BasicFormatter< Char, AF >::parse_arg_index (const Char *& s) inline private
Definition at line 3537 of file format.h.
References fmt::arg(), FMT_THROW, and fmt::internal::parse_nonnegative_int().
template<typename Char , typename AF > internal::Arg fmt::BasicFormatter< Char, AF >::parse_arg_name (const Char *& s) inline private
Definition at line 3549 of file format.h.
References fmt::arg(), FMT_THROW, and fmt::internal::is_name_start().
template<typename CharType, typename ArgFormatter> BasicWriter<Char>& fmt::BasicFormatter< CharType, ArgFormatter >::writer () inline
Returns a reference to the writer associated with this formatter.
Definition at line 2069 of file format.h.
Member Data Documentation
template<typename CharType, typename ArgFormatter> internal::ArgMap<Char> fmt::BasicFormatter< CharType, ArgFormatter >::map_ private
Definition at line 2041 of file format.h.
template<typename CharType, typename ArgFormatter> BasicWriter<Char>& fmt::BasicFormatter< CharType, ArgFormatter >::writer_ private
Definition at line 2040 of file format.h.
The documentation for this class was generated from the following file:
format.h