NGL: ngl::Plane Class Reference
ngl::Plane Class Reference
#include <Plane.h>
Public Member Functions
Plane (const Vec3 &_v1, const Vec3 &_v2, const Vec3 &_v3) noexcept
ctor passing in 3 vectors for the plane
Plane () noexcept
default ctor
~Plane () noexcept
dtor (not used)
void setPoints (const Vec3 &_v1, const Vec3 &_v2, const Vec3 &_v3) noexcept
set the plane from 3 points
void setNormalPoint (const Vec3 &_normal, const Vec3 &_point) noexcept
set the plane from a normal and a point
void setFloats (Real _a, Real _b, Real _c, Real _d) noexcept
set the plane from the co-efficients
Real distance (const Vec3 &_p) const noexcept
get the distance from the point _p to the plane
Vec3 getNormal () const noexcept
accesor to get the normal
Vec3 getPoint () const noexcept
accesor to get the point
Real getD () const noexcept
accesor to get D
Private Attributes
Vec3 m_normal
the normal of the plane
Vec3 m_point
the point position of the normal / plane
Real m_d
the co-efficient of the plane
Detailed Description
Definition at line 41 of file Plane.h.
Constructor & Destructor Documentation
ngl::Plane::Plane (const Vec3 & _v1, const Vec3 & _v2, const Vec3 & _v3) noexcept
ctor passing in 3 vectors for the plane
Parameters
[in] _v1 the first Point
[in] _v2 the second Point
[in] _v3 the third Point
Definition at line 31 of file Plane.cpp.
References setPoints().
ngl::Plane::Plane () noexcept
default ctor
Definition at line 26 of file Plane.cpp.
ngl::Plane::~Plane () noexcept
dtor (not used)
Definition at line 37 of file Plane.cpp.
Member Function Documentation
Real ngl::Plane::distance (const Vec3 & _p) const noexcept
get the distance from the point _p to the plane
Parameters
[in] _p the position to check agains
Returns
the distance from point to plane
Definition at line 75 of file Plane.cpp.
References ngl::Vec3::inner(), m_d, and m_normal.
Real ngl::Plane::getD () const inline noexcept
accesor to get D
Returns
the m_d
Definition at line 104 of file Plane.h.
Vec3 ngl::Plane::getNormal () const inline noexcept
accesor to get the normal
Returns
the normal
Definition at line 93 of file Plane.h.
Vec3 ngl::Plane::getPoint () const inline noexcept
accesor to get the point
Returns
the point
Definition at line 99 of file Plane.h.
void ngl::Plane::setFloats (Real _a, Real _b, Real _c, Real _d) noexcept
set the plane from the co-efficients
Parameters
[in] _a the first co-efficient
[in] _b the second co-efficient
[in] _c the third co-efficient
[in] _d the fourth co-efficient
Definition at line 62 of file Plane.cpp.
References ngl::Vec3::length(), m_d, m_normal, ngl::Vec3::normalize(), and ngl::Vec3::set().
void ngl::Plane::setNormalPoint (const Vec3 & _normal, const Vec3 & _point) noexcept
set the plane from a normal and a point
Parameters
[in] _normal the normal
[in] _point the point
Definition at line 54 of file Plane.cpp.
References ngl::Vec3::inner(), m_d, m_normal, m_point, and ngl::Vec3::normalize().
void ngl::Plane::setPoints (const Vec3 & _v1, const Vec3 & _v2, const Vec3 & _v3) noexcept
set the plane from 3 points
Parameters
[in] _v1 the first point
[in] _v2 the second point
[in] _v3 the third point
Definition at line 42 of file Plane.cpp.
References ngl::Vec3::cross(), ngl::Vec3::inner(), m_d, m_normal, m_point, and ngl::Vec3::normalize().
Member Data Documentation
Real ngl::Plane::m_d private
the co-efficient of the plane
Definition at line 119 of file Plane.h.
Vec3 ngl::Plane::m_normal private
the normal of the plane
Definition at line 111 of file Plane.h.
Vec3 ngl::Plane::m_point private
the point position of the normal / plane
Definition at line 115 of file Plane.h.
The documentation for this class was generated from the following files:
Plane.h
Plane.cpp