NGL: fmt::internal::FormatterBase Class Reference
fmt::internal::FormatterBase Class Reference
#include <format.h>
Protected Member Functions
const ArgList & args () const
FormatterBase (const ArgList &args)
Arg next_arg (const char *&error)
Arg get_arg (unsigned arg_index, const char *&error)
bool check_no_auto_index (const char *&error)
template<typename Char >
void write (BasicWriter< Char > &w, const Char *start, const Char *end)
Private Member Functions
FMT_API Arg do_get_arg (unsigned arg_index, const char *&error)
Private Attributes
ArgList args_
int next_arg_index_
Detailed Description
Definition at line 1932 of file format.h.
Constructor & Destructor Documentation
fmt::internal::FormatterBase::FormatterBase (const ArgList & args) inline explicit protected
Definition at line 1943 of file format.h.
Member Function Documentation
const ArgList& fmt::internal::FormatterBase::args () const inline protected
Definition at line 1941 of file format.h.
bool fmt::internal::FormatterBase::check_no_auto_index (const char *& error) inline protected
Definition at line 1962 of file format.h.
FMT_FUNC Arg fmt::internal::FormatterBase::do_get_arg (unsigned arg_index, const char *& error) private
Definition at line 456 of file format.cc.
References fmt::arg(), fmt::internal::Value::NAMED_ARG, fmt::internal::Value::NONE, fmt::internal::Value::pointer, and fmt::internal::Arg::type.
Arg fmt::internal::FormatterBase::get_arg (unsigned arg_index, const char *& error) inline protected
Definition at line 1958 of file format.h.
Arg fmt::internal::FormatterBase::next_arg (const char *& error) inline protected
Definition at line 1949 of file format.h.
References fmt::internal::to_unsigned().
template<typename Char > void fmt::internal::FormatterBase::write (BasicWriter< Char > & w, const Char * start, const Char * end) inline protected
Definition at line 1972 of file format.h.
References fmt::internal::to_unsigned().
Member Data Documentation
ArgList fmt::internal::FormatterBase::args_ private
Definition at line 1934 of file format.h.
int fmt::internal::FormatterBase::next_arg_index_ private
Definition at line 1935 of file format.h.
The documentation for this class was generated from the following files:
format.h
format.cc