NGL: FileWriteStream Class Reference
FileWriteStream Class Reference
Wrapper of C file stream for input using fread().
#include <filewritestream.h>
Public Types
typedef char Ch
Character type. Only support char.
Public Member Functions
FileWriteStream (std::FILE *fp, char *buffer, size_t bufferSize)
void Put (char c)
void PutN (char c, size_t n)
void Flush ()
char Peek () const
char Take ()
size_t Tell () const
char * PutBegin ()
size_t PutEnd (char *)
Private Member Functions
FileWriteStream (const FileWriteStream &)
FileWriteStream & operator= (const FileWriteStream &)
Private Attributes
std::FILE * fp_
char * buffer_
char * bufferEnd_
char * current_
Detailed Description
Wrapper of C file stream for input using fread().
Note
implements Stream concept
Definition at line 27 of file filewritestream.h.
Member Typedef Documentation
typedef char FileWriteStream::Ch
Character type. Only support char.
Definition at line 29 of file filewritestream.h.
Constructor & Destructor Documentation
FileWriteStream::FileWriteStream (std::FILE * fp, char * buffer, size_t bufferSize) inline
Definition at line 31 of file filewritestream.h.
References fp_, and RAPIDJSON_ASSERT.
FileWriteStream::FileWriteStream (const FileWriteStream &) private
Member Function Documentation
void FileWriteStream::Flush () inline
Definition at line 58 of file filewritestream.h.
References buffer_, current_, and fp_.
FileWriteStream& FileWriteStream::operator= (const FileWriteStream &) private
char FileWriteStream::Peek () const inline
Definition at line 70 of file filewritestream.h.
References RAPIDJSON_ASSERT.
void FileWriteStream::Put (char c) inline
Definition at line 35 of file filewritestream.h.
References bufferEnd_, current_, and Flush().
char* FileWriteStream::PutBegin () inline
Definition at line 73 of file filewritestream.h.
References RAPIDJSON_ASSERT.
size_t FileWriteStream::PutEnd (char *) inline
Definition at line 74 of file filewritestream.h.
References FileWriteStream(), operator=(), and RAPIDJSON_ASSERT.
void FileWriteStream::PutN (char c, size_t n) inline
Definition at line 42 of file filewritestream.h.
References bufferEnd_, current_, and Flush().
char FileWriteStream::Take () inline
Definition at line 71 of file filewritestream.h.
References RAPIDJSON_ASSERT.
size_t FileWriteStream::Tell () const inline
Definition at line 72 of file filewritestream.h.
References RAPIDJSON_ASSERT.
Member Data Documentation
char* FileWriteStream::buffer_ private
Definition at line 82 of file filewritestream.h.
char* FileWriteStream::bufferEnd_ private
Definition at line 83 of file filewritestream.h.
char* FileWriteStream::current_ private
Definition at line 84 of file filewritestream.h.
std::FILE* FileWriteStream::fp_ private
Definition at line 81 of file filewritestream.h.
The documentation for this class was generated from the following file:
filewritestream.h