NGL: ngl::NGLInit Class Reference
ngl::NGLInit Class Reference
a class to initialise all of the ngl elements includeing GLEW if needed as well vbo prims this class is a singletone so can only be created once
#include <NGLInit.h>
Protected Member Functions
NGLInit ()
dtor
~NGLInit ()
dtor
Protected Member Functions inherited from ngl::Singleton< NGLInit >
Singleton ()
Constructor.
virtual ~Singleton ()
Destructor.
Friends
class Singleton< NGLInit >
Additional Inherited Members
Public Member Functions inherited from ngl::Singleton< NGLInit >
Singleton (const Singleton &)=delete
Singleton & operator= (const Singleton &)=delete
Static Public Member Functions inherited from ngl::Singleton< NGLInit >
static NGLInit * instance ()
Get the instance.
Static Protected Member Functions inherited from ngl::Singleton< NGLInit >
static void killSingleton ()
Static Protected Attributes inherited from ngl::Singleton< NGLInit >
static NGLInit * s_instance
unique instance of the singleton
Detailed Description
a class to initialise all of the ngl elements includeing GLEW if needed as well vbo prims this class is a singletone so can only be created once
Author
Jonathan Macey
Version
4.0
Date
Last Revision 19/11/09 changed the whole lib to be NGL not GraphicsLib so change names to reflect 29/09/09 Updated to meet NCCA Coding standard
Definition at line 42 of file NGLInit.h.
Constructor & Destructor Documentation
ngl::NGLInit::NGLInit () protected
dtor
Definition at line 39 of file NGLInit.cpp.
References ngl::SimpleVAO::create(), ngl::MultiBufferVAO::create(), ngl::SimpleIndexVAO::create(), GL_MAJOR_VERSION, GL_MINOR_VERSION, GLEW_OK, GLEW_VERSION, glewExperimental, glewGetErrorString(), glewGetString(), glewInit(), glewIsSupported(), glGetIntegerv(), and ngl::VAOFactory::registerVAOCreator().
ngl::NGLInit::~NGLInit () protected
dtor
Definition at line 75 of file NGLInit.cpp.
Friends And Related Function Documentation
friend class Singleton< NGLInit > friend
Definition at line 44 of file NGLInit.h.
The documentation for this class was generated from the following files:
NGLInit.h
NGLInit.cpp