NGL: ngl::Logger::Impl Class Reference
ngl::Logger::Impl Class Reference
Public Member Functions
Impl (const std::string &_fname) noexcept
void write (const std::string &_text) noexcept
void writeLineNumber () noexcept
void writeTimeStamp () noexcept
std::string currentTime () noexcept
void setColour (Colours c) noexcept
Public Attributes
bool m_logFileAndConsole
bool m_logFile
bool m_logConsole
bool m_timeStamp
bool m_lineNumber
bool m_disableColours
Colours m_colour
char x
std::ofstream m_file
std::string m_timeString
std::string m_logfileName
unsigned int m_lineNumberCount
unsigned int m_pad
TeeStream m_output
Detailed Description
Definition at line 12 of file Logger.cpp.
Constructor & Destructor Documentation
ngl::Logger::Impl::Impl (const std::string & _fname) noexcept
Definition at line 40 of file Logger.cpp.
Member Function Documentation
std::string ngl::Logger::Impl::currentTime () noexcept
Definition at line 71 of file Logger.cpp.
void ngl::Logger::Impl::setColour (Colours c) noexcept
Definition at line 113 of file Logger.cpp.
References ngl::BLUE, ngl::CNORMAL, ngl::CYAN, ngl::GREEN, ngl::MAGENTA, ngl::RED, ngl::RESET, ngl::WHITE, and ngl::YELLOW.
void ngl::Logger::Impl::write (const std::string & _text) noexcept
Definition at line 106 of file Logger.cpp.
References setColour().
void ngl::Logger::Impl::writeLineNumber () noexcept
Definition at line 86 of file Logger.cpp.
References setColour().
void ngl::Logger::Impl::writeTimeStamp () noexcept
Definition at line 96 of file Logger.cpp.
References currentTime(), and setColour().
Member Data Documentation
Colours ngl::Logger::Impl::m_colour
Definition at line 22 of file Logger.cpp.
bool ngl::Logger::Impl::m_disableColours
Definition at line 21 of file Logger.cpp.
std::ofstream ngl::Logger::Impl::m_file
Definition at line 24 of file Logger.cpp.
bool ngl::Logger::Impl::m_lineNumber
Definition at line 20 of file Logger.cpp.
unsigned int ngl::Logger::Impl::m_lineNumberCount
Definition at line 27 of file Logger.cpp.
bool ngl::Logger::Impl::m_logConsole
Definition at line 18 of file Logger.cpp.
bool ngl::Logger::Impl::m_logFile
Definition at line 17 of file Logger.cpp.
bool ngl::Logger::Impl::m_logFileAndConsole
Definition at line 16 of file Logger.cpp.
std::string ngl::Logger::Impl::m_logfileName
Definition at line 26 of file Logger.cpp.
TeeStream ngl::Logger::Impl::m_output
Definition at line 29 of file Logger.cpp.
unsigned int ngl::Logger::Impl::m_pad
Definition at line 28 of file Logger.cpp.
bool ngl::Logger::Impl::m_timeStamp
Definition at line 19 of file Logger.cpp.
std::string ngl::Logger::Impl::m_timeString
Definition at line 25 of file Logger.cpp.
char ngl::Logger::Impl::x
Definition at line 23 of file Logger.cpp.
The documentation for this class was generated from the following file:
Logger.cpp