NGL: ngl::Vec2 Class Reference
ngl::Vec2 Class Reference
simple Vec2 encapsulates a 3 float object like glsl Vec2 but not maths use the Vec2 class for maths and the asVec2 to return a Vec2
#include <Vec2.h>
Public Member Functions
void set (Real _x, Real _y) noexcept
sets the Vec2 component from 3 values
void set (const Vec2 &_v) noexcept
set from another Vec2
void set (const Vec4 &_v) noexcept
set from another Vector
void set (const Vec2 *_v) noexcept
set from another Vec2
Vec2 (const Vec2 &_v) noexcept
copy ctor
Vec2 (Real _x=0.0, Real _y=0.0) noexcept
initialise the constructor from 3 or 4 Real
Vec2 (Real _x) noexcept
ctor using a single float all components are set to the value _x
void null () noexcept
clears the Vec2 to 0,0,0
Real & operator[] (int _i) noexcept
[] index operator to access the index component of the Vec2
const Real & operator[] (int _i) const noexcept
[] index operator to access the index component of the Vec2
void operator+= (const Vec2 &_v) noexcept
+= operator add Vec2 v to current Vec2
void operator-= (const Vec2 &_v) noexcept
-= operator this-=v
Vec2 operator* (const Real &_i) const noexcept
this * i for each element
Real length () const noexcept
returns the length of the vector
Real lengthSquared () const noexcept
returns the length squared of the vector (no sqrt so quicker)
Vec2 operator+ (const Vec2 &_v) const noexcept
operator add Vec2+Vec2
Vec2 operator/ (Real _v) const noexcept
divide Vec2 components by a scalar
void operator/= (Real _v) noexcept
divide this Vec2 components by a scalar
void operator*= (Real _v) noexcept
multiply this Vec2 components by a scalar
Vec2 operator- (const Vec2 &_v) const noexcept
subtraction operator subtract vevtor-Vec2
Vec2 operator* (const Vec2 &_v) const noexcept
operator mult vevtor*Vec2
Vec2 & operator= (const Vec2 &_v) noexcept
assignment operator set the current Vec2 to rhs
Vec2 operator- () const noexcept
negate the Vec2 components
bool operator== (const Vec2 &_v) const noexcept
check for equality uses FCompare (from Util.h) as float values
bool operator!= (const Vec2 &_v) const noexcept
not equal check
Vec2 operator/ (const Vec2 &_v) const noexcept
\ operator div Vec2/Vec2
Vec2 operator* (Real _i) const noexcept
this * i for each element
void normalize () noexcept
Normalize the vector using
.
Real dot (const Vec2 &_b) const noexcept
return this dotted with _b
Real * openGL () noexcept
accesor to the m_openGL matrix returns the address of the 0th element
Public Attributes
Real m_x
x component of the Vec2
Real m_y
y component of the Vec2
std::array< Real, 2 > m_openGL
array of four floats mapped to the x,y,z,w components of the Vec2 useful for openGL fv data types this is mapped as a union to the following
m_x == m_openGL[0]
m_y == m_openGL[1]
Detailed Description
simple Vec2 encapsulates a 3 float object like glsl Vec2 but not maths use the Vec2 class for maths and the asVec2 to return a Vec2
Definition at line 49 of file Vec2.h.
Constructor & Destructor Documentation
ngl::Vec2::Vec2 (const Vec2 & _v) inline noexcept
copy ctor
Parameters
[in] _v the value to set
Definition at line 81 of file Vec2.h.
ngl::Vec2::Vec2 (Real _x = 0.0, Real _y = 0.0) inline noexcept
initialise the constructor from 3 or 4 Real
Parameters
[in] _x x value
[in] _y y value
[in] _w 1.0f default so acts as a points
Definition at line 91 of file Vec2.h.
ngl::Vec2::Vec2 (Real _x) inline noexcept
ctor using a single float all components are set to the value _x
Parameters
[in] _x the value to set all components
Definition at line 98 of file Vec2.h.
Member Function Documentation
Real ngl::Vec2::dot (const Vec2 & _b) const noexcept
return this dotted with _b
Parameters
[in] _b vector to dot current vector with
Returns
the dot product
Definition at line 177 of file Vec2.cpp.
References m_x, and m_y.
Real ngl::Vec2::length () const noexcept
returns the length of the vector
Returns
Definition at line 195 of file Vec2.cpp.
References m_x, and m_y.
Real ngl::Vec2::lengthSquared () const noexcept
returns the length squared of the vector (no sqrt so quicker)
Returns
Definition at line 184 of file Vec2.cpp.
References m_x, and m_y.
void ngl::Vec2::normalize () noexcept
Normalize the vector using
.
Definition at line 164 of file Vec2.cpp.
References m_x, m_y, and NGL_ASSERT.
void ngl::Vec2::null () noexcept
clears the Vec2 to 0,0,0
Definition at line 49 of file Vec2.cpp.
References m_x, and m_y.
Real* ngl::Vec2::openGL () inline noexcept
accesor to the m_openGL matrix returns the address of the 0th element
Definition at line 239 of file Vec2.h.
bool ngl::Vec2::operator!= (const Vec2 & _v) const noexcept
not equal check
Parameters
[in] _v the Vec2 to check against
Returns
true of false
Definition at line 125 of file Vec2.cpp.
References FCompare, m_x, and m_y.
Vec2 ngl::Vec2::operator* (const Real & _i) const noexcept
this * i for each element
Parameters
[in] _i the scalar to mult by
Returns
Vec2
Vec2 ngl::Vec2::operator* (const Vec2 & _v) const noexcept
operator mult vevtor*Vec2
Parameters
[in] _v the value to mult
Returns
new Vec2 this*v
Definition at line 133 of file Vec2.cpp.
References m_x, m_y, and Vec2().
Vec2 ngl::Vec2::operator* (Real _i) const noexcept
this * i for each element
Parameters
[in] _i the scalar to mult by
Returns
Vec2
Definition at line 148 of file Vec2.cpp.
References m_x, m_y, and Vec2().
void ngl::Vec2::operator*= (Real _v) noexcept
multiply this Vec2 components by a scalar
Parameters
[in] _v the scalar to multiply by sets the Vec2 to Vec2 V(x*v,y*v)
Definition at line 86 of file Vec2.cpp.
References m_x, and m_y.
Vec2 ngl::Vec2::operator+ (const Vec2 & _v) const noexcept
operator add Vec2+Vec2
Parameters
[in] &_v the value to add
Returns
the Vec2 + v
Definition at line 105 of file Vec2.cpp.
References m_x, m_y, and Vec2().
void ngl::Vec2::operator+= (const Vec2 & _v) noexcept
+= operator add Vec2 v to current Vec2
Parameters
[in] &_v Vec2 to add
Definition at line 72 of file Vec2.cpp.
References m_x, and m_y.
Vec2 ngl::Vec2::operator- (const Vec2 & _v) const noexcept
subtraction operator subtract vevtor-Vec2
Parameters
[in] &_v the value to sub
Returns
this - v
Definition at line 111 of file Vec2.cpp.
References m_x, m_y, and Vec2().
Vec2 ngl::Vec2::operator- () const noexcept
negate the Vec2 components
Definition at line 65 of file Vec2.cpp.
References m_x, m_y, and Vec2().
void ngl::Vec2::operator-= (const Vec2 & _v) noexcept
-= operator this-=v
Parameters
[in] &_v Vec2 to subtract
Definition at line 92 of file Vec2.cpp.
References m_x, and m_y.
Vec2 ngl::Vec2::operator/ (Real _v) const noexcept
divide Vec2 components by a scalar
Parameters
[in] _v the scalar to divide by
Returns
a Vec2 V(x/v,y/v,z/v,w)
Definition at line 99 of file Vec2.cpp.
References m_x, m_y, and Vec2().
Vec2 ngl::Vec2::operator/ (const Vec2 & _v) const noexcept
\ operator div Vec2/Vec2
Parameters
[in] _v the value to div by
Returns
Vec2 / Vec2
Definition at line 142 of file Vec2.cpp.
References m_x, m_y, and Vec2().
void ngl::Vec2::operator/= (Real _v) noexcept
divide this Vec2 components by a scalar
Parameters
[in] _v the scalar to divide by sets the Vec2 to Vec2 V(x/v,y/v)
Definition at line 79 of file Vec2.cpp.
References m_x, m_y, and NGL_ASSERT.
Vec2 & ngl::Vec2::operator= (const Vec2 & _v) noexcept
assignment operator set the current Vec2 to rhs
Parameters
[in] _v the Vec2 to set
Returns
a new Vec2
Definition at line 156 of file Vec2.cpp.
References m_x, and m_y.
bool ngl::Vec2::operator== (const Vec2 & _v) const noexcept
check for equality uses FCompare (from Util.h) as float values
Parameters
[in] _v the Vec2 to check against
Returns
true or false
Definition at line 117 of file Vec2.cpp.
References FCompare, m_x, and m_y.
Real & ngl::Vec2::operator[] (int _i) noexcept
[] index operator to access the index component of the Vec2
Returns
this[x] as a Real
Definition at line 56 of file Vec2.cpp.
References m_x, and NGL_ASSERT.
const Real& ngl::Vec2::operator[] (int _i) const inline noexcept
[] index operator to access the index component of the Vec2
Returns
this[x] as a Real
Definition at line 116 of file Vec2.h.
References ngl::operator*(), and ngl::operator==().
void ngl::Vec2::set (Real _x, Real _y) noexcept
sets the Vec2 component from 3 values
Parameters
[in] _x the x component
[in] _y the y component
Definition at line 29 of file Vec2.cpp.
void ngl::Vec2::set (const Vec2 & _v) noexcept
set from another Vec2
Parameters
[in] _v the Vec2 to set from
Definition at line 36 of file Vec2.cpp.
void ngl::Vec2::set (const Vec4 & _v) noexcept
set from another Vector
Parameters
[in] _v the Vec2 to set from
void ngl::Vec2::set (const Vec2 * _v) noexcept
set from another Vec2
Parameters
[in] _v the Vec2 to set from
Definition at line 42 of file Vec2.cpp.
Member Data Documentation
std::array<Real,2> ngl::Vec2::m_openGL
array of four floats mapped to the x,y,z,w components of the Vec2 useful for openGL fv data types this is mapped as a union to the following
m_x == m_openGL[0]
m_y == m_openGL[1]
Definition at line 273 of file Vec2.h.
Real ngl::Vec2::m_x
x component of the Vec2
Note
I've made this public as some compilers automatically make the anonymous unions public whereas clang++ complains see this post http://jonmacey.blogspot.com/2011/03/anonymous-union-struct-weirdness.html
Definition at line 256 of file Vec2.h.
Real ngl::Vec2::m_y
y component of the Vec2
Definition at line 260 of file Vec2.h.
The documentation for this class was generated from the following files:
Vec2.h
Vec2.cpp