NGL: std::numeric_limits< fmt::internal::DummyInt > Class Template Reference
std::numeric_limits< fmt::internal::DummyInt > Class Template Reference
#include <format.h>
Static Public Member Functions
template<typename T >
static bool isinfinity (T x)
template<typename T >
static bool isnotanumber (T x)
static bool isnegative (double x)
Detailed Description
template<>
class std::numeric_limits< fmt::internal::DummyInt >
Definition at line 322 of file format.h.
Member Function Documentation
template<typename T > static bool std::numeric_limits< fmt::internal::DummyInt >::isinfinity (T x) inline static
Definition at line 327 of file format.h.
References fmt::internal::_finite(), fmt::internal::const_check(), and fmt::internal::isinf().
static bool std::numeric_limits< fmt::internal::DummyInt >::isnegative (double x) inline static
Definition at line 350 of file format.h.
References fmt::internal::_ecvt_s(), fmt::internal::const_check(), and fmt::internal::signbit().
template<typename T > static bool std::numeric_limits< fmt::internal::DummyInt >::isnotanumber (T x) inline static
Definition at line 340 of file format.h.
References fmt::internal::_isnan(), fmt::internal::const_check(), and fmt::internal::isnan().
The documentation for this class was generated from the following file:
format.h