NGL: ngl::Mat3 Class Reference
ngl::Mat3 Class Reference
Mat3 basic 3x3 matrix for certain glsl ops.
#include <Mat3.h>
Public Member Functions
Mat3 () noexcept
ctor will always create an identity matrix
Mat3 (Real _00, Real _01, Real _02, Real _10, Real _11, Real _12, Real _20, Real _21, Real _22) noexcept
ctor passing in value
Mat3 (const Mat4 &_m) noexcept
copy ctor from mat4 will copy left up and fwd vectors
Mat3 (const Mat3 &_m) noexcept
copy ctor with reference object
Mat3 (const Real _m) noexcept
copy ctor with Real useful for Matrix m=1; for identity or Matrix m=3.5 for uniform scale
void setAtXY (GLint _x, GLint _y, Real _equals) noexcept
set the value at m_m[_x][_y] to _equals
const Mat3 & null () noexcept
clear the matrix to all 0
const Mat3 & identity () noexcept
make the matrix m the identity matrix
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
Mat3 operator* (const Mat3 &_m) const noexcept
operator for matrix multiplication
const Mat3 & operator*= (const Mat3 &_m) noexcept
operator to mult this matrix by value _m
Mat3 operator+ (const Mat3 &_m) const noexcept
operator to add two matrices together
const Mat3 & operator+= (const Mat3 &_m) noexcept
+= operator
Mat3 operator* (Real _i) const noexcept
operator to mult matrix by a scalar
const Mat3 & operator*= (Real _i) noexcept
*= operator with a scalar value
Vec3 operator* (const Vec3 &_v) const noexcept
multiply this by a Vec3
const Mat3 & transpose () noexcept
method to transpose the matrix
void rotateX (Real _deg) noexcept
set this matrix to a rotation matrix in the X axis for value _deg note the matrix should be set to identity before doing this
void rotateY (Real _deg) noexcept
set this matrix to a rotation matrix in the Y axis for value _deg note the matrix should be set to identity before doing this
void rotateZ (Real _deg) noexcept
set this matrix to a rotation matrix in the Z axis for value _deg note the matrix should be set to identity before doing this
void scale (Real _x, Real _y, Real _z) noexcept
set the matrix scale values
Real determinant () const noexcept
get the determinant of the matrix
Mat3 inverse () noexcept
set the matrix to be the inverse
void euler (Real _angle, Real _x, Real _y, Real _z) noexcept
axis / angle rotation using the Euler method
Real * openGL () noexcept
accesor to the openGL matrix
Vec3 getLeftVector () const noexcept
get the left vector of the matrix (-ve 1st Row)
Vec3 getRightVector () const noexcept
get the right vector of the matrix (1nd Row)
Vec3 getUpVector () const noexcept
get the up vector of the matrix (2nd Row)
Vec3 getDownVector () const noexcept
get the down vector of the matrix (-ve 2nd Row)
Vec3 getForwardVector () const noexcept
get the forward vector of the matrix (-ve 3rd Row)
Vec3 getBackVector () const noexcept
get the back vector of the matrix (3nd Row)
Public Attributes
Real m_m [3][3]
Mat3 element m_m as a 4x4 array mapped by union to m_nn elements and m_openGL.
std::array< Real, 9 > m_openGL
The matrix in m_openGL 16 Real array format usefull for OpenGL fv formats mapped to m_m[][] elements and m_xx elements.
Real m_00
individual matrix element maps to m_m[0][0] or m_openGL[0]
Real m_01
individual matrix element maps to m_m[0][1] or m_openGL[1]
Real m_02
individual matrix element maps to m_m[0][2] or m_openGL[2]
Real m_10
individual matrix element maps to m_m[1][0] or m_openGL[4]
Real m_11
individual matrix element maps to m_m[1][1] or m_openGL[5]
Real m_12
individual matrix element maps to m_m[1][2] or m_openGL[6]
Real m_20
individual matrix element maps to m_m[2][0] or m_openGL[8]
Real m_21
individual matrix element maps to m_m[2][1] or m_openGL[9]
Real m_22
individual matrix element maps to m_m[2][2] or m_openGL[10]
Friends
class Transformation
class Quaternion
class Camera
Detailed Description
Mat3 basic 3x3 matrix for certain glsl ops.
Author
Jonathan Macey
Version
1.0
Date
27/10/11
Definition at line 43 of file Mat3.h.
Constructor & Destructor Documentation
ngl::Mat3::Mat3 () noexcept
ctor will always create an identity matrix
Definition at line 36 of file Mat3.cpp.
References m_00, m_11, m_22, and m_m.
ngl::Mat3::Mat3 (Real _00, Real _01, Real _02, Real _10, Real _11, Real _12, Real _20, Real _21, Real _22) noexcept
ctor passing in value
Definition at line 57 of file Mat3.cpp.
References m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, and m_22.
ngl::Mat3::Mat3 (const Mat4 & _m) noexcept
copy ctor from mat4 will copy left up and fwd vectors
Definition at line 44 of file Mat3.cpp.
References m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, and m_22.
ngl::Mat3::Mat3 (const Mat3 & _m) noexcept
copy ctor with reference object
Definition at line 72 of file Mat3.cpp.
References m_m.
ngl::Mat3::Mat3 (const Real _m) noexcept
copy ctor with Real useful for Matrix m=1; for identity or Matrix m=3.5 for uniform scale
Definition at line 80 of file Mat3.cpp.
References m_00, m_11, m_22, and m_m.
Member Function Documentation
Real ngl::Mat3::determinant () const noexcept
get the determinant of the matrix
Returns
the determinat
Definition at line 338 of file Mat3.cpp.
References m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, and m_22.
void ngl::Mat3::euler (Real _angle, Real _x, Real _y, Real _z) noexcept
axis / angle rotation using the Euler method
Parameters
[in] _angle the angle in degree to rotate
[in] _x part of the axis should be normalised before call
[in] _y part of the axis should be normalised before call
[in] _z part of the axis should be normalised before call
Definition at line 320 of file Mat3.cpp.
References m_m, and ngl::radians().
Vec3 ngl::Mat3::getBackVector () const noexcept
get the back vector of the matrix (3nd Row)
Returns
the up vector
Definition at line 404 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::getDownVector () const noexcept
get the down vector of the matrix (-ve 2nd Row)
Returns
the up vector
Definition at line 392 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::getForwardVector () const noexcept
get the forward vector of the matrix (-ve 3rd Row)
Returns
the up vector
Definition at line 398 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::getLeftVector () const noexcept
get the left vector of the matrix (-ve 1st Row)
Returns
the up vector
Definition at line 374 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::getRightVector () const noexcept
get the right vector of the matrix (1nd Row)
Returns
the up vector
Definition at line 379 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::getUpVector () const noexcept
get the up vector of the matrix (2nd Row)
Returns
the up vector
Definition at line 385 of file Mat3.cpp.
References m_openGL.
const Mat3 & ngl::Mat3::identity () noexcept
make the matrix m the identity matrix
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
Definition at line 105 of file Mat3.cpp.
References m_00, m_11, m_22, and m_m.
Mat3 ngl::Mat3::inverse () noexcept
set the matrix to be the inverse
Definition at line 346 of file Mat3.cpp.
References determinant(), m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, m_22, and Mat3().
const Mat3 & ngl::Mat3::null () noexcept
clear the matrix to all 0
Definition at line 99 of file Mat3.cpp.
References m_m.
Real* ngl::Mat3::openGL () inline noexcept
accesor to the openGL matrix
Returns
a pointer to m_openGL[0]
Definition at line 188 of file Mat3.h.
Mat3 ngl::Mat3::operator* (const Mat3 & _m) const noexcept
operator for matrix multiplication
Parameters
[in] _m the matrix to multiply the current one by
Returns
this*_m
Definition at line 115 of file Mat3.cpp.
References m_m.
Mat3 ngl::Mat3::operator* (Real _i) const noexcept
operator to mult matrix by a scalar
Parameters
[in] _i the scalar to multiply by
Returns
this*_i
Definition at line 210 of file Mat3.cpp.
References m_openGL.
Vec3 ngl::Mat3::operator* (const Vec3 & _v) const noexcept
multiply this by a Vec3
Parameters
[in] _v the vector to multiply
Returns
Vector M*V
Definition at line 304 of file Mat3.cpp.
References m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, m_22, ngl::Vec3::m_x, ngl::Vec3::m_y, and ngl::Vec3::m_z.
const Mat3 & ngl::Mat3::operator*= (const Mat3 & _m) noexcept
operator to mult this matrix by value _m
Parameters
[in] _m the matrix to multiplt
Returns
a new matrix this*_m
Definition at line 132 of file Mat3.cpp.
References m_00, m_01, m_02, m_10, m_11, m_12, m_20, m_21, and m_22.
const Mat3 & ngl::Mat3::operator*= (Real _i) noexcept
*= operator with a scalar value
Parameters
[in] _i the scalar to multiply by
Returns
the matrix*i
Definition at line 225 of file Mat3.cpp.
References m_m.
Mat3 ngl::Mat3::operator+ (const Mat3 & _m) const noexcept
operator to add two matrices together
Parameters
[in] _m the matrix to add
Returns
this+_m
Definition at line 182 of file Mat3.cpp.
References m_openGL.
const Mat3 & ngl::Mat3::operator+= (const Mat3 & _m) noexcept
+= operator
Parameters
[in] _m the matrix to add
Returns
this+m
Definition at line 197 of file Mat3.cpp.
References m_openGL.
void ngl::Mat3::rotateX (Real _deg) noexcept
set this matrix to a rotation matrix in the X axis for value _deg note the matrix should be set to identity before doing this
Parameters
[in] _deg the value to be rotated by in degrees
Definition at line 258 of file Mat3.cpp.
References m_11, m_12, m_21, m_22, and ngl::radians().
void ngl::Mat3::rotateY (Real _deg) noexcept
set this matrix to a rotation matrix in the Y axis for value _deg note the matrix should be set to identity before doing this
Parameters
[in] _deg the value to be rotated by in degrees
Definition at line 270 of file Mat3.cpp.
References m_00, m_02, m_20, m_22, and ngl::radians().
void ngl::Mat3::rotateZ (Real _deg) noexcept
set this matrix to a rotation matrix in the Z axis for value _deg note the matrix should be set to identity before doing this
Parameters
[in] _deg the value to be rotated by in degrees
Definition at line 282 of file Mat3.cpp.
References m_00, m_01, m_10, m_11, and ngl::radians().
void ngl::Mat3::scale (Real _x, Real _y, Real _z) noexcept
set the matrix scale values
Parameters
[in] _x the scale value in the _x
[in] _y the scale value in the _y
[in] _z the scale value in the _z
Definition at line 296 of file Mat3.cpp.
References m_00, m_11, and m_22.
void ngl::Mat3::setAtXY (GLint _x, GLint _y, Real _equals) noexcept
set the value at m_m[_x][_y] to _equals
Parameters
[in] _x the x index into the array
[in] _y the y index into the array
[in] _equals the value to set to
Todo:
replace this with function operator overload ()
Definition at line 94 of file Mat3.cpp.
References m_m.
const Mat3 & ngl::Mat3::transpose () noexcept
method to transpose the matrix
Definition at line 241 of file Mat3.cpp.
References m_m.
Friends And Related Function Documentation
friend class Camera friend
Definition at line 225 of file Mat3.h.
friend class Quaternion friend
Definition at line 224 of file Mat3.h.
friend class Transformation friend
Definition at line 223 of file Mat3.h.
Member Data Documentation
Real ngl::Mat3::m_00
individual matrix element maps to m_m[0][0] or m_openGL[0]
Definition at line 256 of file Mat3.h.
Real ngl::Mat3::m_01
individual matrix element maps to m_m[0][1] or m_openGL[1]
Definition at line 260 of file Mat3.h.
Real ngl::Mat3::m_02
individual matrix element maps to m_m[0][2] or m_openGL[2]
Definition at line 264 of file Mat3.h.
Real ngl::Mat3::m_10
individual matrix element maps to m_m[1][0] or m_openGL[4]
Definition at line 268 of file Mat3.h.
Real ngl::Mat3::m_11
individual matrix element maps to m_m[1][1] or m_openGL[5]
Definition at line 272 of file Mat3.h.
Real ngl::Mat3::m_12
individual matrix element maps to m_m[1][2] or m_openGL[6]
Definition at line 276 of file Mat3.h.
Real ngl::Mat3::m_20
individual matrix element maps to m_m[2][0] or m_openGL[8]
Definition at line 280 of file Mat3.h.
Real ngl::Mat3::m_21
individual matrix element maps to m_m[2][1] or m_openGL[9]
Definition at line 284 of file Mat3.h.
Real ngl::Mat3::m_22
individual matrix element maps to m_m[2][2] or m_openGL[10]
Definition at line 288 of file Mat3.h.
Real ngl::Mat3::m_m[3][3]
Mat3 element m_m as a 4x4 array mapped by union to m_nn elements and m_openGL.
Definition at line 237 of file Mat3.h.
std::array<Real,9> ngl::Mat3::m_openGL
Initial value:
={{
                                 1.0f,0.0f,0.0f,
                                 0.0f,1.0f,0.0f,
                                 0.0f,0.0f,1.0f
                                 }}
The matrix in m_openGL 16 Real array format usefull for OpenGL fv formats mapped to m_m[][] elements and m_xx elements.
Definition at line 243 of file Mat3.h.
The documentation for this class was generated from the following files:
Mat3.h
Mat3.cpp