NGL: internal::Double Class Reference
internal::Double Class Reference
#include <ieee754.h>
Public Member Functions
Double ()
Double (double d)
Double (uint64_t u)
double Value () const
uint64_t Uint64Value () const
double NextPositiveDouble () const
bool Sign () const
uint64_t Significand () const
int Exponent () const
bool IsNan () const
bool IsInf () const
bool IsNormal () const
bool IsZero () const
uint64_t IntegerSignificand () const
int IntegerExponent () const
uint64_t ToBias () const
Static Public Member Functions
static unsigned EffectiveSignificandSize (int order)
Private Attributes
union {
double d_
uint64_t u_
};
Static Private Attributes
static const int kSignificandSize = 52
static const int kExponentBias = 0x3FF
static const int kDenormalExponent = 1 - kExponentBias
static const uint64_t kSignMask = RAPIDJSON_UINT64_C2(0x80000000, 0x00000000)
static const uint64_t kExponentMask = RAPIDJSON_UINT64_C2(0x7FF00000, 0x00000000)
static const uint64_t kSignificandMask = RAPIDJSON_UINT64_C2(0x000FFFFF, 0xFFFFFFFF)
static const uint64_t kHiddenBit = RAPIDJSON_UINT64_C2(0x00100000, 0x00000000)
Detailed Description
Definition at line 23 of file ieee754.h.
Constructor & Destructor Documentation
internal::Double::Double () inline
Definition at line 25 of file ieee754.h.
internal::Double::Double (double d) inline
Definition at line 26 of file ieee754.h.
internal::Double::Double (uint64_t u) inline
Definition at line 27 of file ieee754.h.
Member Function Documentation
static unsigned internal::Double::EffectiveSignificandSize (int order) inline static
Definition at line 50 of file ieee754.h.
int internal::Double::Exponent () const inline
Definition at line 39 of file ieee754.h.
References kExponentBias, kExponentMask, kSignificandSize, and u_.
int internal::Double::IntegerExponent () const inline
Definition at line 47 of file ieee754.h.
References Exponent(), IsNormal(), kDenormalExponent, and kSignificandSize.
uint64_t internal::Double::IntegerSignificand () const inline
Definition at line 46 of file ieee754.h.
References IsNormal(), kHiddenBit, and Significand().
bool internal::Double::IsInf () const inline
Definition at line 42 of file ieee754.h.
References kExponentMask, Significand(), and u_.
bool internal::Double::IsNan () const inline
Definition at line 41 of file ieee754.h.
References kExponentMask, Significand(), and u_.
bool internal::Double::IsNormal () const inline
Definition at line 43 of file ieee754.h.
References kExponentMask, Significand(), and u_.
bool internal::Double::IsZero () const inline
Definition at line 44 of file ieee754.h.
References kExponentMask, kSignificandMask, and u_.
double internal::Double::NextPositiveDouble () const inline
Definition at line 32 of file ieee754.h.
References Double(), RAPIDJSON_ASSERT, Sign(), and u_.
bool internal::Double::Sign () const inline
Definition at line 37 of file ieee754.h.
References kSignMask, and u_.
uint64_t internal::Double::Significand () const inline
Definition at line 38 of file ieee754.h.
References kSignificandMask, and u_.
uint64_t internal::Double::ToBias () const inline
Definition at line 48 of file ieee754.h.
References kSignMask, and u_.
uint64_t internal::Double::Uint64Value () const inline
Definition at line 30 of file ieee754.h.
References u_.
double internal::Double::Value () const inline
Definition at line 29 of file ieee754.h.
References d_.
Member Data Documentation
union { ... }
double internal::Double::d_
Definition at line 69 of file ieee754.h.
const int internal::Double::kDenormalExponent = 1 - kExponentBias static private
Definition at line 62 of file ieee754.h.
const int internal::Double::kExponentBias = 0x3FF static private
Definition at line 61 of file ieee754.h.
const uint64_t internal::Double::kExponentMask = RAPIDJSON_UINT64_C2(0x7FF00000, 0x00000000) static private
Definition at line 64 of file ieee754.h.
const uint64_t internal::Double::kHiddenBit = RAPIDJSON_UINT64_C2(0x00100000, 0x00000000) static private
Definition at line 66 of file ieee754.h.
const uint64_t internal::Double::kSignificandMask = RAPIDJSON_UINT64_C2(0x000FFFFF, 0xFFFFFFFF) static private
Definition at line 65 of file ieee754.h.
const int internal::Double::kSignificandSize = 52 static private
Definition at line 60 of file ieee754.h.
const uint64_t internal::Double::kSignMask = RAPIDJSON_UINT64_C2(0x80000000, 0x00000000) static private
Definition at line 63 of file ieee754.h.
uint64_t internal::Double::u_
Definition at line 70 of file ieee754.h.
The documentation for this class was generated from the following file:
ieee754.h