NGL: fmt::BufferedFile Class Reference
fmt::BufferedFile Class Reference
#include <posix.h>
Classes
struct Proxy
Public Member Functions
BufferedFile () FMT_NOEXCEPT
~BufferedFile () FMT_NOEXCEPT
BufferedFile (Proxy p) FMT_NOEXCEPT
BufferedFile (BufferedFile &f) FMT_NOEXCEPT
BufferedFile & operator= (Proxy p)
BufferedFile & operator= (BufferedFile &other)
operator Proxy () FMT_NOEXCEPT
BufferedFile (CStringRef filename, CStringRef mode)
void close ()
FILE * get () const FMT_NOEXCEPT
int() fileno () const
void print (CStringRef format_str, const ArgList &args)
Private Member Functions
BufferedFile (FILE *f)
Private Attributes
FILE * file_
Friends
class File
Detailed Description
Definition at line 81 of file posix.h.
Constructor & Destructor Documentation
fmt::BufferedFile::BufferedFile (FILE * f) inline explicit private
Definition at line 87 of file posix.h.
fmt::BufferedFile::BufferedFile () inline
Definition at line 91 of file posix.h.
References FMT_NOEXCEPT.
fmt::BufferedFile::~BufferedFile ()
Definition at line 66 of file posix.cc.
References file_, FMT_SYSTEM, and fmt::report_system_error().
fmt::BufferedFile::BufferedFile (Proxy p) inline
Definition at line 109 of file posix.h.
fmt::BufferedFile::BufferedFile (BufferedFile & f) inline
Definition at line 112 of file posix.h.
fmt::BufferedFile::BufferedFile (fmt::CStringRef filename, fmt::CStringRef mode)
Definition at line 71 of file posix.cc.
References fmt::BasicCStringRef< Char >::c_str(), file_, FMT_RETRY_VAL, and FMT_SYSTEM.
Member Function Documentation
void fmt::BufferedFile::close ()
Definition at line 78 of file posix.cc.
References file_, and FMT_SYSTEM.
int fmt::BufferedFile::fileno () const
Definition at line 90 of file posix.cc.
References file_, FMT_ARGS, and FMT_POSIX_CALL.
FILE* fmt::BufferedFile::get () const inline
Definition at line 163 of file posix.h.
References int().
fmt::BufferedFile::operator Proxy () inline
Definition at line 133 of file posix.h.
References FMT_DISALLOW_COPY_AND_ASSIGN, and FMT_NOEXCEPT.
BufferedFile& fmt::BufferedFile::operator= (Proxy p) inline
Definition at line 117 of file posix.h.
References fmt::BufferedFile::Proxy::file.
BufferedFile& fmt::BufferedFile::operator= (BufferedFile & other) inline
Definition at line 124 of file posix.h.
References file_.
void fmt::BufferedFile::print (CStringRef format_str, const ArgList & args) inline
Definition at line 169 of file posix.h.
References FMT_VARIADIC, and fmt::print().
Friends And Related Function Documentation
friend class File friend
Definition at line 85 of file posix.h.
Member Data Documentation
FILE* fmt::BufferedFile::file_ private
Definition at line 83 of file posix.h.
The documentation for this class was generated from the following files:
posix.h
posix.cc