NGL: fmt::StrFormatSpec< Char > Class Template Reference
fmt::StrFormatSpec< Char > Class Template Reference
#include <format.h>
Public Member Functions
template<typename FillChar >
StrFormatSpec (const Char *str, unsigned width, FillChar fill)
const Char * str () const
Public Member Functions inherited from fmt::AlignSpec
AlignSpec (unsigned width, wchar_t fill, Alignment align=ALIGN_DEFAULT)
Alignment align () const
int precision () const
Public Member Functions inherited from fmt::WidthSpec
WidthSpec (unsigned width, wchar_t fill)
unsigned width () const
wchar_t fill () const
Private Attributes
const Char * str_
Additional Inherited Members
Public Attributes inherited from fmt::AlignSpec
Alignment align_
Public Attributes inherited from fmt::WidthSpec
unsigned width_
wchar_t fill_
Detailed Description
template<typename Char>
class fmt::StrFormatSpec< Char >
Definition at line 1676 of file format.h.
Constructor & Destructor Documentation
template<typename Char> template<typename FillChar > fmt::StrFormatSpec< Char >::StrFormatSpec (const Char * str, unsigned width, FillChar fill) inline
Definition at line 1682 of file format.h.
References fmt::internal::convert().
Member Function Documentation
template<typename Char> const Char* fmt::StrFormatSpec< Char >::str () const inline
Definition at line 1687 of file format.h.
References fmt::bin(), fmt::hex(), fmt::hexu(), fmt::oct(), and fmt::pad().
Member Data Documentation
template<typename Char> const Char* fmt::StrFormatSpec< Char >::str_ private
Definition at line 1678 of file format.h.
The documentation for this class was generated from the following file:
format.h