NGL: ngl::Transformation Class Reference
ngl::Transformation Class Reference
Transformation describes a transformation (translate, scale, rotation) modifed by j macey and included into NGL.
#include <Transformation.h>
Public Member Functions
Transformation () noexcept
Constructor.
Transformation (const Transformation &_t) noexcept
Copy Constructor.
Transformation & operator= (const Transformation &_t) noexcept
assignment operator
void setScale (const Vec3 &_scale) noexcept
method to set the scale value in the transform
void setScale (const Vec4 &_scale) noexcept
void setScale (Real _x, Real _y, Real _z) noexcept
method to set the scale value in the transform
void addScale (const Vec3 &_scale) noexcept
method to add to the existing the scale value in the transform
void addScale (Real _x, Real _y, Real _z) noexcept
method to add to the existing the scale value in the transform
void setPosition (const Vec4 &_position) noexcept
method to set the position
void setPosition (const Vec3 &_position) noexcept
method to set the position
void setPosition (Real _x, Real _y, Real _z) noexcept
method to set the position value in the transform
void addPosition (const Vec4 &_position) noexcept
method add to the existing set the position
void addPosition (const Vec3 &_position) noexcept
method add to the existing set the position
void addPosition (Real _x, Real _y, Real _z) noexcept
method to add to the existing position value in the transform
void setMatrix (const Mat4 &_m) noexcept
void setRotation (const Vec3 &_rotation) noexcept
method to set the rotation
void setRotation (const Vec4 &_rotation) noexcept
void setRotation (Real _x, Real _y, Real _z) noexcept
method to set the rotation value in the transform
void addRotation (const Vec3 &_rotation) noexcept
method to add to the existing rotation
void addRotation (Real _x, Real _y, Real _z) noexcept
method to add to the existing rotation value in the transform
void reset () noexcept
a method to set all the transforms to the identity
Vec3 getScale () const noexcept
function to get the scale
Vec3 getPosition () const noexcept
function to get the position
Vec3 getRotation () const noexcept
function to get the rotation
Mat4 getMatrix () noexcept
function to get the matrix. It computes the matrix if it's dirty
Mat4 getTransposeMatrix () noexcept
function to get the transpose matrix. It computes the transpose matrix if it's dirty
Mat4 getInverseMatrix () noexcept
function to get the inverse matrix. It computes the inverse matrix if it's dirty
void operator*= (const Transformation &_m) noexcept
*= operator
Transformation operator* (const Transformation &_m) noexcept
operator for Transform multiplication will do a matrix multiplication on each of the matrices
void loadMatrixToShader (const std::string &_param, const ActiveMatrix &_which=ActiveMatrix::NORMAL) noexcept
load the current transform matrix to the shader
void loadGlobalAndCurrentMatrixToShader (const std::string &_param, Transformation &_global, const ActiveMatrix &_which=ActiveMatrix::NORMAL) noexcept
load the current * global transform matrix to the shader
Protected Member Functions
void computeMatrices () noexcept
method to compute the matrix, transpose and inverse matrix. set the m_bIsMatrixComputed variable to true.
Protected Attributes
Vec3 m_position
position
Vec3 m_scale
scale
Vec3 m_rotation
rotation
bool m_isMatrixComputed
boolean defines if the matrix is dirty or not
Mat4 m_matrix
matrix transformation
Mat4 m_transposeMatrix
transpose matrix transformation
Mat4 m_inverseMatrix
inverse matrix transformation
Friends
class Vec4
Detailed Description
Transformation describes a transformation (translate, scale, rotation) modifed by j macey and included into NGL.
Author
Vincent Bonnet
Version
1.5
Date
14/03/10 Last Revision 14/03/10
Definition at line 43 of file Transformation.h.
Constructor & Destructor Documentation
ngl::Transformation::Transformation () noexcept
Constructor.
Definition at line 27 of file Transformation.cpp.
References computeMatrices(), m_inverseMatrix, m_isMatrixComputed, m_matrix, m_position, m_rotation, m_scale, and m_transposeMatrix.
ngl::Transformation::Transformation (const Transformation & _t) noexcept
Copy Constructor.
Definition at line 40 of file Transformation.cpp.
References m_inverseMatrix, m_isMatrixComputed, m_matrix, m_position, m_rotation, m_scale, and m_transposeMatrix.
Member Function Documentation
void ngl::Transformation::addPosition (const Vec4 & _position) noexcept
method add to the existing set the position
Parameters
[in] _position position
void ngl::Transformation::addPosition (const Vec3 & _position) noexcept
method add to the existing set the position
Parameters
[in] _position position
Definition at line 132 of file Transformation.cpp.
References m_isMatrixComputed, and m_position.
void ngl::Transformation::addPosition (Real _x, Real _y, Real _z) noexcept
method to add to the existing position value in the transform
Parameters
[in] _x x position value
[in] _y y position value
[in] _z z position value
Definition at line 137 of file Transformation.cpp.
References m_isMatrixComputed, m_position, ngl::Vec3::m_x, ngl::Vec3::m_y, and ngl::Vec3::m_z.
void ngl::Transformation::addRotation (const Vec3 & _rotation) noexcept
method to add to the existing rotation
Parameters
[in] _rotation rotation
Note
each value is an axis rotation as the values are calculated mRotationX * mRotationY * mRotationZ;
Definition at line 169 of file Transformation.cpp.
References m_isMatrixComputed, and m_rotation.
void ngl::Transformation::addRotation (Real _x, Real _y, Real _z) noexcept
method to add to the existing rotation value in the transform
Note
each value is an axis rotation as the values are calculated mRotationX * mRotationY * mRotationZ;
Parameters
[in] _x x rotation value
[in] _y y rotation value
[in] _z z rotation value
Definition at line 174 of file Transformation.cpp.
References m_isMatrixComputed, m_rotation, ngl::Vec3::m_x, ngl::Vec3::m_y, and ngl::Vec3::m_z.
void ngl::Transformation::addScale (const Vec3 & _scale) noexcept
method to add to the existing the scale value in the transform
Parameters
[in] _scale the scale value to set for the transform
Definition at line 98 of file Transformation.cpp.
References m_isMatrixComputed, and m_scale.
void ngl::Transformation::addScale (Real _x, Real _y, Real _z) noexcept
method to add to the existing the scale value in the transform
Parameters
[in] _x x scale value
[in] _y y scale value
[in] _z z scale value
Definition at line 105 of file Transformation.cpp.
References m_isMatrixComputed, m_scale, ngl::Vec3::m_x, ngl::Vec3::m_y, and ngl::Vec3::m_z.
void ngl::Transformation::computeMatrices () protected noexcept
method to compute the matrix, transpose and inverse matrix. set the m_bIsMatrixComputed variable to true.
Definition at line 194 of file Transformation.cpp.
References m_inverseMatrix, m_isMatrixComputed, ngl::Mat4::m_m, m_matrix, m_position, m_rotation, m_scale, m_transposeMatrix, ngl::Vec3::m_x, ngl::Vec3::m_y, ngl::Vec3::m_z, ngl::Mat4::rotateX(), ngl::Mat4::rotateY(), ngl::Mat4::rotateZ(), ngl::Mat4::scale(), ngl::Mat4::translate(), and ngl::Mat4::transpose().
Mat4 ngl::Transformation::getInverseMatrix () inline noexcept
function to get the inverse matrix. It computes the inverse matrix if it's dirty
Returns
the inverse matrix
Definition at line 192 of file Transformation.h.
References ngl::NORMAL, and ngl::operator*().
Mat4 ngl::Transformation::getMatrix () inline noexcept
function to get the matrix. It computes the matrix if it's dirty
Returns
the matrix
Definition at line 182 of file Transformation.h.
Vec3 ngl::Transformation::getPosition () const inline noexcept
function to get the position
Returns
the position
Definition at line 172 of file Transformation.h.
Vec3 ngl::Transformation::getRotation () const inline noexcept
function to get the rotation
Returns
the rotation
Definition at line 177 of file Transformation.h.
Vec3 ngl::Transformation::getScale () const inline noexcept
function to get the scale
Returns
the scale
Definition at line 167 of file Transformation.h.
Mat4 ngl::Transformation::getTransposeMatrix () inline noexcept
function to get the transpose matrix. It computes the transpose matrix if it's dirty
Returns
the transpose matrix
Definition at line 187 of file Transformation.h.
void ngl::Transformation::loadGlobalAndCurrentMatrixToShader (const std::string & _param, Transformation & _global, const ActiveMatrix & _which = ActiveMatrix::NORMAL) noexcept
load the current * global transform matrix to the shader
Parameters
[in] _param the name of the parameter to set (varying mat4)
[in] _which which matrix mode to use
Definition at line 294 of file Transformation.cpp.
References computeMatrices(), getInverseMatrix(), getMatrix(), getTransposeMatrix(), ngl::Singleton< ShaderLib >::instance(), ngl::INVERSE, ngl::NORMAL, ngl::ShaderLib::setShaderParamFromMat4(), and ngl::TRANSPOSE.
void ngl::Transformation::loadMatrixToShader (const std::string & _param, const ActiveMatrix & _which = ActiveMatrix::NORMAL) noexcept
load the current transform matrix to the shader
Parameters
[in] _param the name of the parameter to set (varying mat4)
[in] _which which matrix mode to use
Definition at line 267 of file Transformation.cpp.
References computeMatrices(), ngl::Singleton< ShaderLib >::instance(), ngl::INVERSE, m_inverseMatrix, m_matrix, m_transposeMatrix, ngl::NORMAL, ngl::ShaderLib::setShaderParamFromMat4(), and ngl::TRANSPOSE.
Transformation ngl::Transformation::operator* (const Transformation & _m) noexcept
operator for Transform multiplication will do a matrix multiplication on each of the matrices
Note
this is not const as we need to check that the members are calculated before we do the multiplication. This is deliberate
Parameters
[in] _m the Transform to multiply the current one by
Returns
all the transform matrix members * my _m members
Definition at line 256 of file Transformation.cpp.
References computeMatrices(), m_inverseMatrix, m_isMatrixComputed, m_matrix, and m_transposeMatrix.
void ngl::Transformation::operator*= (const Transformation & _m) noexcept
*= operator
Parameters
_m the transformation to combine
transpose matrix transformation
inverse matrix transformation
Definition at line 242 of file Transformation.cpp.
References computeMatrices(), m_inverseMatrix, m_isMatrixComputed, m_matrix, and m_transposeMatrix.
Transformation & ngl::Transformation::operator= (const Transformation & _t) noexcept
assignment operator
Definition at line 53 of file Transformation.cpp.
References m_inverseMatrix, m_isMatrixComputed, m_matrix, m_position, m_rotation, m_scale, and m_transposeMatrix.
void ngl::Transformation::reset () noexcept
a method to set all the transforms to the identity
Definition at line 184 of file Transformation.cpp.
References computeMatrices(), m_isMatrixComputed, m_position, m_rotation, and m_scale.
void ngl::Transformation::setMatrix (const Mat4 & _m) noexcept
method to set the matrix directly
Parameters
[in] _m the matrix to set the m_transform to need to also re-compute the others
Definition at line 70 of file Transformation.cpp.
References m_isMatrixComputed, m_matrix, m_transposeMatrix, and ngl::Mat4::transpose().
void ngl::Transformation::setPosition (const Vec4 & _position) noexcept
method to set the position
Parameters
[in] _position position
Definition at line 115 of file Transformation.cpp.
References m_isMatrixComputed, and m_position.
void ngl::Transformation::setPosition (const Vec3 & _position) noexcept
method to set the position
Parameters
[in] _position position
Definition at line 120 of file Transformation.cpp.
References m_isMatrixComputed, and m_position.
void ngl::Transformation::setPosition (Real _x, Real _y, Real _z) noexcept
method to set the position value in the transform
Parameters
[in] _x x position value
[in] _y y position value
[in] _z z position value
Definition at line 125 of file Transformation.cpp.
References m_isMatrixComputed, m_position, and ngl::Vec3::set().
void ngl::Transformation::setRotation (const Vec3 & _rotation) noexcept
method to set the rotation
Parameters
[in] _rotation rotation
Note
each value is an axis rotation as the values are calculated mRotationX * mRotationY * mRotationZ;
Definition at line 148 of file Transformation.cpp.
References m_isMatrixComputed, and m_rotation.
void ngl::Transformation::setRotation (const Vec4 & _rotation) noexcept
Definition at line 153 of file Transformation.cpp.
References m_isMatrixComputed, and m_rotation.
void ngl::Transformation::setRotation (Real _x, Real _y, Real _z) noexcept
method to set the rotation value in the transform
Note
each value is an axis rotation as the values are calculated mRotationX * mRotationY * mRotationZ;
Parameters
[in] _x x rotation value
[in] _y y rotation value
[in] _z z rotation value
Definition at line 160 of file Transformation.cpp.
References m_isMatrixComputed, m_rotation, and ngl::Vec3::set().
void ngl::Transformation::setScale (const Vec3 & _scale) noexcept
method to set the scale value in the transform
Parameters
[in] _scale the scale value to set for the transform
Definition at line 79 of file Transformation.cpp.
References m_isMatrixComputed, and m_scale.
void ngl::Transformation::setScale (const Vec4 & _scale) noexcept
Definition at line 85 of file Transformation.cpp.
References m_isMatrixComputed, and m_scale.
void ngl::Transformation::setScale (Real _x, Real _y, Real _z) noexcept
method to set the scale value in the transform
Parameters
[in] _x x scale value
[in] _y y scale value
[in] _z z scale value
Definition at line 91 of file Transformation.cpp.
References m_isMatrixComputed, m_scale, and ngl::Vec3::set().
Friends And Related Function Documentation
friend class Vec4 friend
Definition at line 45 of file Transformation.h.
Member Data Documentation
Mat4 ngl::Transformation::m_inverseMatrix protected
inverse matrix transformation
Definition at line 249 of file Transformation.h.
bool ngl::Transformation::m_isMatrixComputed protected
boolean defines if the matrix is dirty or not
Definition at line 237 of file Transformation.h.
Mat4 ngl::Transformation::m_matrix protected
matrix transformation
Definition at line 241 of file Transformation.h.
Vec3 ngl::Transformation::m_position protected
position
Definition at line 225 of file Transformation.h.
Vec3 ngl::Transformation::m_rotation protected
rotation
Definition at line 233 of file Transformation.h.
Vec3 ngl::Transformation::m_scale protected
scale
Definition at line 229 of file Transformation.h.
Mat4 ngl::Transformation::m_transposeMatrix protected
transpose matrix transformation
Definition at line 245 of file Transformation.h.
The documentation for this class was generated from the following files:
Transformation.h
Transformation.cpp