NGL: fmt::internal Namespace Reference
fmt::internal Namespace Reference
Classes
struct Arg
struct ArgArray
struct ArgArray< N, false >
struct ArgArray< N, true >
class ArgConverter
class ArgFormatterBase
class ArgMap
struct ArgType
class BasicCharTraits
struct BasicData
class CharConverter
class CharTraits
class CharTraits< char >
class CharTraits< wchar_t >
struct Conditional
struct Conditional< false, T, F >
struct ConvertToInt
struct ConvertToIntImpl
struct ConvertToIntImpl2
struct ConvertToIntImpl2< T, true >
struct ConvertToIntImpl< T, true >
struct DummyInt
struct DummyStream
struct EnableIf
struct EnableIf< true, T >
struct False
class FixedBuffer
class FormatBuf
class FormatterBase
struct IntChecker
struct IntChecker< true >
struct IntTraits
struct is_same
struct is_same< T, T >
class IsZeroInt
struct LConvCheck
class MakeArg
struct MakeUnsigned
class MakeValue
class MemoryBuffer
struct NamedArg
struct Not
struct Not< false >
struct NoThousandsSep
struct Null
class PrecisionHandler
class RuntimeError
struct SignChecker
struct SignChecker< false >
class StringBuffer
class ThousandsSep
struct TypeSelector
struct TypeSelector< false >
struct Value
struct WCharHelper
struct WCharHelper< T, wchar_t >
class WidthHandler
Typedefs
typedef std::numeric_limits< fmt::internal::DummyInt > FPUtil
typedef BasicData Data
typedef char Yes[1]
typedef char No[2]
Enumerations
enum { INLINE_BUFFER_SIZE = 500 }
Functions
FMT_FUNC void format_system_error (Writer &out, int error_code, StringRef message) FMT_NOEXCEPT
DummyInt signbit (...)
DummyInt _ecvt_s (...)
DummyInt isinf (...)
DummyInt _finite (...)
DummyInt isnan (...)
DummyInt _isnan (...)
template<typename T >
T const_check (T value)
FMT_SPECIALIZE_MAKE_UNSIGNED (char, unsigned char)
FMT_SPECIALIZE_MAKE_UNSIGNED (signed char, unsigned char)
FMT_SPECIALIZE_MAKE_UNSIGNED (short, unsigned short)
FMT_SPECIALIZE_MAKE_UNSIGNED (int, unsigned)
FMT_SPECIALIZE_MAKE_UNSIGNED (long, unsigned long)
FMT_SPECIALIZE_MAKE_UNSIGNED (LongLong, ULongLong)
template<typename Int >
MakeUnsigned< Int >::Type to_unsigned (Int value)
template<typename T >
T * make_ptr (T *ptr, std::size_t)
template<typename T >
bool is_negative (T value)
FMT_API void report_unknown_type (char code, const char *type)
unsigned count_digits (uint64_t n)
template<typename UInt , typename Char , typename ThousandsSep >
void format_decimal (Char *buffer, UInt value, unsigned num_digits, ThousandsSep thousands_sep)
template<typename UInt , typename Char >
void format_decimal (Char *buffer, UInt value, unsigned num_digits)
template<typename T >
T & get ()
Yes & convert (fmt::ULongLong)
No & convert (...)
FMT_DISABLE_CONVERSION_TO_INT (float)
FMT_DISABLE_CONVERSION_TO_INT (double)
FMT_DISABLE_CONVERSION_TO_INT (long double)
template<typename LConv >
StringRef thousands_sep (LConv *lc, LConvCheck< char *LConv::*,&LConv::thousands_sep >=0)
fmt::StringRef thousands_sep (...)
template<typename Formatter , typename Char , typename T >
void format_arg (Formatter &, const Char *, const T &)
uint64_t make_type ()
template<typename T >
uint64_t make_type (const T &arg)
uint64_t make_type (FMT_GEN15(FMT_ARG_TYPE_DEFAULT))
template<typename Char >
bool is_name_start (Char c)
template<typename Char >
unsigned parse_nonnegative_int (const Char *&s)
void require_numeric_argument (const Arg &arg, char spec)
template<typename Char >
void check_sign (const Char *&s, const Arg &arg)
FMT_FUNC void write (std::ostream &os, Writer &w)
Yes & convert (std::ostream &)
No & operator<< (std::ostream &, int)
Typedef Documentation
typedef BasicData fmt::internal::Data
Definition at line 851 of file format.h.
typedef std::numeric_limits<fmt::internal::DummyInt> fmt::internal::FPUtil
Definition at line 298 of file format.h.
typedef char fmt::internal::No[2]
Definition at line 1063 of file format.h.
typedef char fmt::internal::Yes[1]
Definition at line 1062 of file format.h.
Enumeration Type Documentation
anonymous enum
Enumerator
INLINE_BUFFER_SIZE
Definition at line 571 of file format.h.
Function Documentation
DummyInt fmt::internal::_ecvt_s (...) inline
Definition at line 303 of file format.h.
DummyInt fmt::internal::_finite (...) inline
Definition at line 305 of file format.h.
DummyInt fmt::internal::_isnan (...) inline
Definition at line 307 of file format.h.
template<typename Char > void fmt::internal::check_sign (const Char *& s, const Arg & arg)
Definition at line 3512 of file format.h.
References FMT_THROW, fmt::format(), require_numeric_argument(), fmt::internal::Arg::type, fmt::internal::Value::UINT, and fmt::internal::Value::ULONG_LONG.
template<typename T > T fmt::internal::const_check (T value) inline
Definition at line 312 of file format.h.
Yes& fmt::internal::convert (std::ostream &)
Yes& fmt::internal::convert (fmt::ULongLong)
No& fmt::internal::convert (...)
unsigned fmt::internal::count_digits (uint64_t n) inline
Definition at line 864 of file format.h.
References fmt::internal::BasicData< T >::POWERS_OF_10_32, and to_unsigned().
fmt::internal::FMT_DISABLE_CONVERSION_TO_INT (float)
fmt::internal::FMT_DISABLE_CONVERSION_TO_INT (double)
fmt::internal::FMT_DISABLE_CONVERSION_TO_INT (long double)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (char , unsigned char)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (signed char, unsigned char)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (short , unsigned short)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (int , unsigned)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (long , unsigned long)
fmt::internal::FMT_SPECIALIZE_MAKE_UNSIGNED (LongLong , ULongLong)
template<typename Formatter , typename Char , typename T > void fmt::internal::format_arg (Formatter & , const Char * , const T &)
Definition at line 1164 of file format.h.
References FMT_STATIC_ASSERT.
template<typename UInt , typename Char , typename ThousandsSep > void fmt::internal::format_decimal (Char * buffer, UInt value, unsigned num_digits, ThousandsSep thousands_sep) inline
Definition at line 919 of file format.h.
References fmt::internal::BasicData< T >::DIGITS, and thousands_sep().
template<typename UInt , typename Char > void fmt::internal::format_decimal (Char * buffer, UInt value, unsigned num_digits) inline
Definition at line 944 of file format.h.
References format_decimal().
FMT_FUNC void fmt::internal::format_system_error (Writer & out, int error_code, StringRef message)
Definition at line 219 of file format.cc.
References fmt::format_system_error().
template<typename T > T& fmt::internal::get ()
template<typename Char > bool fmt::internal::is_name_start (Char c) inline
Definition at line 3477 of file format.h.
template<typename T > bool fmt::internal::is_negative (T value) inline
Definition at line 811 of file format.h.
DummyInt fmt::internal::isinf (...) inline
Definition at line 304 of file format.h.
DummyInt fmt::internal::isnan (...) inline
Definition at line 306 of file format.h.
template<typename T > T* fmt::internal::make_ptr (T * ptr, std::size_t) inline
Definition at line 581 of file format.h.
uint64_t fmt::internal::make_type () inline
Definition at line 2098 of file format.h.
template<typename T > uint64_t fmt::internal::make_type (const T & arg) inline
Definition at line 2101 of file format.h.
uint64_t fmt::internal::make_type (FMT_GEN15(FMT_ARG_TYPE_DEFAULT)) inline
Definition at line 2153 of file format.h.
No& fmt::internal::operator<< (std::ostream & , int)
template<typename Char > unsigned fmt::internal::parse_nonnegative_int (const Char *& s)
Definition at line 3484 of file format.h.
References FMT_THROW.
FMT_FUNC void fmt::internal::report_unknown_type (char code, const char * type)
Definition at line 296 of file format.cc.
References convert(), fmt::BasicStringRef< Char >::data(), FMT_CATCH, FMT_FUNC, FMT_NOEXCEPT, FMT_THROW, FMT_TRY, fmt::format(), INLINE_BUFFER_SIZE, fmt::Buffer< T >::resize(), fmt::BasicStringRef< Char >::size(), fmt::Buffer< T >::size(), fmt::BasicWriter< Char >::str(), and void().
void fmt::internal::require_numeric_argument (const Arg & arg, char spec) inline
Definition at line 3503 of file format.h.
References FMT_THROW, fmt::format(), fmt::internal::Value::LAST_NUMERIC_TYPE, and fmt::internal::Arg::type.
DummyInt fmt::internal::signbit (...) inline
Definition at line 302 of file format.h.
template<typename LConv > StringRef fmt::internal::thousands_sep (LConv * lc, LConvCheck< char *LConv::*,&LConv::thousands_sep > = 0) inline
Definition at line 1135 of file format.h.
fmt::StringRef fmt::internal::thousands_sep (...) inline
Definition at line 1140 of file format.h.
template<typename Int > MakeUnsigned<Int>::Type fmt::internal::to_unsigned (Int value) inline
Definition at line 564 of file format.h.
References FMT_ASSERT.
void fmt::internal::write (std::ostream & os, Writer & w)
Definition at line 15 of file ostream.cc.
References fmt::BasicWriter< Char >::data(), fmt::BasicWriter< Char >::size(), and to_unsigned().