NGL: AutoUTF< CharType > Struct Template Reference
AutoUTF< CharType > Struct Template Reference
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
#include <encodings.h>
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Static Public Member Functions
template<typename OutputStream >
static RAPIDJSON_FORCEINLINE void Encode (OutputStream &os, unsigned codepoint)
template<typename InputStream >
static RAPIDJSON_FORCEINLINE bool Decode (InputStream &is, unsigned *codepoint)
template<typename InputStream , typename OutputStream >
static RAPIDJSON_FORCEINLINE bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType>
struct AutoUTF< CharType >
Dynamically select encoding according to stream's runtime-specified UTF encoding type.
Note
This class can be used with AutoUTFInputtStream and AutoUTFOutputStream, which provides GetType().
Definition at line 550 of file encodings.h.
Member Typedef Documentation
template<typename CharType > typedef CharType AutoUTF< CharType >::Ch
Definition at line 551 of file encodings.h.
Member Enumeration Documentation
template<typename CharType > anonymous enum
Enumerator
supportUnicode
Definition at line 553 of file encodings.h.
Member Function Documentation
template<typename CharType > template<typename InputStream > static RAPIDJSON_FORCEINLINE bool AutoUTF< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static
Definition at line 565 of file encodings.h.
References UTF8< CharType >::Decode(), and RAPIDJSON_ENCODINGS_FUNC.
template<typename CharType > template<typename OutputStream > static RAPIDJSON_FORCEINLINE void AutoUTF< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static
Definition at line 558 of file encodings.h.
References UTF8< CharType >::Encode(), RAPIDJSON_ENCODINGS_FUNC, and void().
template<typename CharType > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool AutoUTF< CharType >::Validate (InputStream & is, OutputStream & os) inline static
Definition at line 572 of file encodings.h.
References RAPIDJSON_ENCODINGS_FUNC, and UTF8< CharType >::Validate().
The documentation for this struct was generated from the following file:
encodings.h